name: "Artifactory-Build"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Custodian
        run: |
          echo "testing"
          sudo apt install python3.8
          pip3 install tox
          git clone https://github.com/draios/cloud-custodian.git
          ls
          tox -e py38
          source .tox/py38/bin/active
